### ISSUE TITLE
Disk space checks fails with error: "TypeError: disk.check is not a function"

### ISSUE THREAD

**Issue by arcesino** [Financial-Times/node-health-check#133]
Type: Bug report

## What
Setting up disk space check fails with error:
```
TypeError: disk.check is not a function
```

## Details

The following code replicates the bug:
```javascript
const HealthCheck = require("@financial-times/health-check");

const health = new HealthCheck({
    checks: [{
			type: 'disk-space',
			threshold: 80,
			interval: 15000,
			id: 'system-disk-space',
			name: 'System Disk Space Usage',
			severity: 2,
			businessImpact: 'New files may not be saved',
			technicalSummary: 'Something went wrong!',
			panicGuide: 'Don\'t panic'
		}]
});

health.toJSON();
```
The relavant part of the stack trace is:
```
      at node_modules/@financial-times/health-check/lib/check/disk-space.js:36:9
      at DiskSpaceCheck.run (node_modules/@financial-times/health-check/lib/check/disk-space.js:35:10)
      at DiskSpaceCheck.start (node_modules/@financial-times/health-check/lib/check.js:62:8)
      at new Check (node_modules/@financial-times/health-check/lib/check.js:51:8)
      at new DiskSpaceCheck (node_modules/@financial-times/health-check/lib/check/disk-space.js:27:3)
      at node_modules/@financial-times/health-check/lib/health-check.js:34:11
          at Array.map (<anonymous>)
```
## Additional information

I noticed that you are using NPM package [`disk-space#1.1.0`](https://www.npmjs.com/package/disk-space) but looking at the source code of this package, I see there's no a `check` function that can be used. Wondering if you got confused with NPM package [`diskspace`](https://www.npmjs.com/package/diskspace) (no hyphen) which does have a `check` function. I also noticed that, despite this bug, your unit test pass without problems since you are using a Sino mock that provides the `check` function though that package doesn't have a result with `available` property which is used by the actual check.

I will send a PR later with a fix for this.

**Comment by JakeChampion** [comment]
fixed via #145 and #144
